function [allData, scenario, sensors] = curvedroad_Bhanu()
%curvedroad_Bhanu - Returns sensor detections
%    allData = curvedroad_Bhanu returns sensor detections in a structure
%    with time for an internally defined scenario and sensor suite.
%
%    [allData, scenario, sensors] = curvedroad_Bhanu optionally returns
%    the drivingScenario and detection generator objects.

% Generated by MATLAB(R) 9.13 (R2022b) and Automated Driving Toolbox 3.6 (R2022b).
% Generated on: 20-May-2023 18:22:40

% Create the drivingScenario object and ego car
[scenario, egoVehicle] = createDrivingScenario;

% Create all the sensors
[sensors, numSensors] = createSensors(scenario);

allData = struct('Time', {}, 'ActorPoses', {}, 'ObjectDetections', {}, 'LaneDetections', {}, 'PointClouds', {}, 'INSMeasurements', {});
running = true;
while running

    % Generate the target poses of all actors relative to the ego vehicle
    poses = targetPoses(egoVehicle);
    time  = scenario.SimulationTime;

    objectDetections = {};
    laneDetections   = [];
    ptClouds = {};
    insMeas = {};
    isValidTime = false(1, numSensors);

    % Generate detections for each sensor
    for sensorIndex = 1:numSensors
        sensor = sensors{sensorIndex};
        [objectDets, isValidTime(sensorIndex)] = sensor(poses, time);
        numObjects = length(objectDets);
        objectDetections = [objectDetections; objectDets(1:numObjects)]; %#ok<AGROW>
    end

    % Aggregate all detections into a structure for later use
    if any(isValidTime)
        allData(end + 1) = struct( ...
            'Time',       scenario.SimulationTime, ...
            'ActorPoses', actorPoses(scenario), ...
            'ObjectDetections', {objectDetections}, ...
            'LaneDetections', {laneDetections}, ...
            'PointClouds',   {ptClouds}, ... %#ok<AGROW>
            'INSMeasurements',   {insMeas}); %#ok<AGROW>
    end

    % Advance the scenario one time step and exit the loop if the scenario is complete
    running = advance(scenario);
end

% Restart the driving scenario to return the actors to their initial positions.
restart(scenario);

% Release all the sensor objects so they can be used again.
for sensorIndex = 1:numSensors
    release(sensors{sensorIndex});
end

%%%%%%%%%%%%%%%%%%%%
% Helper functions %
%%%%%%%%%%%%%%%%%%%%

% Units used in createSensors and createDrivingScenario
% Distance/Position - meters
% Speed             - meters/second
% Angles            - degrees
% RCS Pattern       - dBsm

function [sensors, numSensors] = createSensors(scenario)
% createSensors Returns all sensor objects to generate detections

% Assign into each sensor the physical and radar profiles for all actors
profiles = actorProfiles(scenario);
sensors{1} = visionDetectionGenerator('SensorIndex', 1, ...
    'SensorLocation', [3.7 0], ...
    'MaxRange', 100, ...
    'DetectorOutput', 'Objects only', ...
    'Intrinsics', cameraIntrinsics([1814.81018227767 1814.81018227767],[320 240],[480 640]), ...
    'ActorProfiles', profiles);
sensors{2} = drivingRadarDataGenerator('SensorIndex', 2, ...
    'MountingLocation', [3.7 0 0.2], ...
    'RangeLimits', [0 100], ...
    'TargetReportFormat', 'Detections', ...
    'FieldOfView', [360 5], ...
    'Profiles', profiles);
numSensors = 2;

function [scenario, egoVehicle] = createDrivingScenario
% createDrivingScenario Returns the drivingScenario defined in the Designer

% Construct a drivingScenario object.
scenario = drivingScenario;

% Add all road segments
roadCenters = [0 -1.75 0;
    83.95 -1.75 0;
    120 -1.75 0;
    201.75 80 0;
    201.75 299.99980286749 0];
headings = [0;0;0;90;90];
marking1 = [laneMarking('Unmarked')
    laneMarking('Unmarked')
    laneMarking('Unmarked')
    laneMarking('Solid', 'Width', 0.125)
    laneMarking('Dashed', 'Width', 0.125)
    laneMarking('SolidDashed', 'Color', [0.98 0.86 0.36], 'Width', 0.125)
    laneMarking('DashedSolid', 'Color', [0.98 0.86 0.36], 'Width', 0.125)
    laneMarking('Dashed', 'Width', 0.125)
    laneMarking('Solid', 'Width', 0.125)
    laneMarking('Unmarked')
    laneMarking('Unmarked')
    laneMarking('Unmarked')];
lanetypes1 = [laneType('Border')
    laneType('Shoulder')
    laneType('Shoulder')
    laneType('Driving')
    laneType('Driving')
    laneType('Restricted')
    laneType('Driving')
    laneType('Driving')
    laneType('Shoulder')
    laneType('Shoulder')
    laneType('Border')];

marking2 = [laneMarking('Unmarked')
    laneMarking('Unmarked')
    laneMarking('Unmarked')
    laneMarking('Solid', 'Width', 0.125)
    laneMarking('Dashed', 'Width', 0.125)
    laneMarking('SolidDashed', 'Color', [0.98 0.86 0.36], 'Width', 0.125)
    laneMarking('DashedSolid', 'Color', [0.98 0.86 0.36], 'Width', 0.125)
    laneMarking('Dashed', 'Width', 0.125)
    laneMarking([laneMarking('Unmarked') laneMarking('Dashed', 'Width', 0.125)], 'SegmentRange', [0.102301854867981 0.897698145132019])
    laneMarking('Solid', 'Width', 0.125)
    laneMarking('Unmarked')
    laneMarking('Unmarked')
    laneMarking('Unmarked')];
lanetypes2 = [laneType('Border')
    laneType('Shoulder')
    laneType('Shoulder')
    laneType('Driving')
    laneType('Driving')
    laneType('Restricted')
    laneType('Driving')
    laneType('Driving')
    laneType('Driving')
    laneType('Shoulder')
    laneType('Shoulder')
    laneType('Border')];

laneSpecifications = [lanespec([6 5], 'Width', [2 0.635 2.5 3.5 3.5 3.5 3.5 3.5 2.5 0.635 2], 'Marking', marking1, 'Type', lanetypes1)
    lanespec([6 6], 'Width', [2 0.635 2.5 3.5 3.5 3.5 3.5 3.5 3.5 2.5 0.635 2], 'Marking', marking2, 'Type', lanetypes2)];
lsConnector = laneSpecConnector('Position', 'Right', 'TaperShape', 'None');
compLaneSpecification = compositeLaneSpec(laneSpecifications, 'Connector', lsConnector, 'SegmentRange', [0.180901328145555 0.819098671854445]);
road(scenario, roadCenters, 'Heading', headings, 'Lanes', compLaneSpecification, 'Name', 'Road');

% Add the ego vehicle
egoVehicle = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [3.15 -8.46 0.01], ...
    'Mesh', driving.scenario.carMesh, ...
    'Name', 'Car');
waypoints = [3.15 -8.46 0.01;
    12.64 -8.59 0.01;
    21.65 -8.52 0.01;
    38.5 -8.5 0;
    54.2 -8.8 0;
    69.3 -8.8 0;
    84.7 -9 0;
    97.4 -9 0;
    114.9 -9.3 0;
    123.9 -8.7 0;
    140.5 -6.3 0;
    156.6 -1.1 0;
    168.5 4.9 0;
    178.6 13.8 0;
    186.6 21 0;
    194.7 31.7 0;
    202 45.2 0;
    206.3 57.6 0;
    209.8 70 0;
    208.8 79.7 0;
    208.8 93.1 0;
    209.6 105 0;
    208.9 118.5 0;
    208.6 131.8 0;
    209.4 145.7 0;
    208.9 156 0];
speed = [30;30;30;30;30;30;30;30;30;30;30;30;30;30;30;30;30;30;30;30;30;30;30;30;30;30];
trajectory(egoVehicle, waypoints, speed);

% Add the non-ego actors
car1 = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [104.68 2.03 0.01], ...
    'Mesh', driving.scenario.carMesh, ...
    'Name', 'Car1');
waypoints = [104.68 2.03 0.01;
    92.4 1.8 0;
    80.3 1.7 0;
    75.2 2 0;
    69.9 1.6 0;
    63.7 1.1 0;
    57.5 1.5 0;
    50.9 1.7 0];
speed = [30;30;30;30;30;30;30;30];
trajectory(car1, waypoints, speed);

