function [allData, scenario, sensor] = ParkingLot1()
%ParkingLot1 - Returns sensor detections
%    allData = ParkingLot1 returns sensor detections in a structure
%    with time for an internally defined scenario and sensor suite.
%
%    [allData, scenario, sensors] = ParkingLot1 optionally returns
%    the drivingScenario and detection generator objects.

% Generated by MATLAB(R) 9.14 (R2023a) and Automated Driving Toolbox 3.7 (R2023a).
% Generated on: 08-Mar-2024 17:06:06

% Create the drivingScenario object and ego car
[scenario, egoVehicle] = createDrivingScenario;

% Create all the sensors
sensor = createSensor(scenario);

allData = struct('Time', {}, 'ActorPoses', {}, 'ObjectDetections', {}, 'LaneDetections', {}, 'PointClouds', {}, 'INSMeasurements', {});
running = true;
while running

    % Generate the target poses of all actors relative to the ego vehicle
    poses = targetPoses(egoVehicle);
    time  = scenario.SimulationTime;

    % Generate detections for the sensor
    laneDetections = [];
    ptClouds = [];
    insMeas = [];
    [objectDetections, isValidTime] = sensor(poses, time);
    numObjects = length(objectDetections);
    objectDetections = objectDetections(1:numObjects);

    % Aggregate all detections into a structure for later use
    if isValidTime
        allData(end + 1) = struct( ...
            'Time',       scenario.SimulationTime, ...
            'ActorPoses', actorPoses(scenario), ...
            'ObjectDetections', {objectDetections}, ...
            'LaneDetections', {laneDetections}, ...
            'PointClouds',   {ptClouds}, ... %#ok<AGROW>
            'INSMeasurements',   {insMeas}); %#ok<AGROW>
    end

    % Advance the scenario one time step and exit the loop if the scenario is complete
    running = advance(scenario);
end

% Restart the driving scenario to return the actors to their initial positions.
restart(scenario);

% Release the sensor object so it can be used again.
release(sensor);

%%%%%%%%%%%%%%%%%%%%
% Helper functions %
%%%%%%%%%%%%%%%%%%%%

% Units used in createSensors and createDrivingScenario
% Distance/Position - meters
% Speed             - meters/second
% Angles            - degrees
% RCS Pattern       - dBsm

function sensor = createSensor(scenario)
% createSensors Returns all sensor objects to generate detections

% Assign into each sensor the physical and radar profiles for all actors
profiles = actorProfiles(scenario);
sensor = visionDetectionGenerator('SensorIndex', 1, ...
    'SensorLocation', [1.785 0], ...
    'DetectorOutput', 'Objects only', ...
    'ActorProfiles', profiles);

function [scenario, egoVehicle] = createDrivingScenario
% createDrivingScenario Returns the drivingScenario defined in the Designer

% Construct a drivingScenario object.
scenario = drivingScenario;

% Add all road segments
roadCenters = [-7.77 -0.01 0;
    40.17 0.19 0];
lanetypes = [laneType('Driving')
    laneType('Parking', 'Color', [0.8 0.8 0.8])];
laneSpecification = lanespec(2, 'Type', lanetypes);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road');

% Add the barriers
barrierCenters = [14.98 -3.56 0;
    9.41 -0.5 0];
barrier(scenario, barrierCenters, ...
    'ClassID', 5, ...
    'Width', 0.1, ...
    'Height', 0.1, ...
    'Mesh', driving.scenario.jerseyBarrierMesh, 'PlotColor', [255 255 255] / 255, 'Name', 'Jersey Barrier');

barrierCenters = [20.65 -3.46 0;
    15.08 -0.4 0];
barrier(scenario, barrierCenters, ...
    'ClassID', 5, ...
    'Width', 0.1, ...
    'Height', 0.1, ...
    'Mesh', driving.scenario.jerseyBarrierMesh, 'PlotColor', [255 255 255] / 255, 'Name', 'Jersey Barrier1');

barrierCenters = [26.32 -3.49 0;
    20.75 -0.43 0];
barrier(scenario, barrierCenters, ...
    'ClassID', 5, ...
    'Width', 0.1, ...
    'Height', 0.1, ...
    'Mesh', driving.scenario.jerseyBarrierMesh, 'PlotColor', [255 255 255] / 255, 'Name', 'Jersey Barrier2');

barrierCenters = [31.95 -3.47 0;
    26.38 -0.41 0];
barrier(scenario, barrierCenters, ...
    'ClassID', 5, ...
    'Width', 0.1, ...
    'Height', 0.1, ...
    'Mesh', driving.scenario.jerseyBarrierMesh, 'PlotColor', [255 255 255] / 255, 'Name', 'Jersey Barrier4');

% Add the ego vehicle
egoVehicle = vehicle(scenario, ...
    'ClassID', 1, ...
    'Length', 4.165, ...
    'Width', 1.778, ...
    'Position', [-6.31 1.73 0.01], ...
    'RearOverhang', 0.74, ...
    'FrontOverhang', 0.74, ...
    'Mesh', driving.scenario.carMesh, ...
    'Name', 'Car');
waypoints = [-6.31 1.73 0.01;
    -0.79 1.73 0.01;
    2.72 1.73 0.01;
    5.75 1.73 0.01;
    9.65 1.73 0.01;
    13.54 1.73 0.01;
    16.79 1.73 0.01;
    19.92 1.73 0.01;
    22.57 1.73 0.01;
    25.66 1.73 0.01;
    29.17 1.73 0;
    32.67 1.73 0.01;
    35.3 1.73 0.01;
    38.13 1.73 0.01];
speed = [30;30;30;30;30;30;30;30;30;30;30;30;30;30];
waittime = [0;0;0;0;0;0;0;0;0;0;0;0;0;0];
trajectory(egoVehicle, waypoints, speed, waittime);

