function [allData, scenario, sensors] = Simulated_Scenario()
%scenario_SS_intersection - Returns sensor detections
%    allData = scenario_SS_intersection returns sensor detections in a structure
%    with time for an internally defined scenario and sensor suite.
%
%    [allData, scenario, sensors] = scenario_SS_intersection optionally returns
%    the drivingScenario and detection generator objects.

% Generated by MATLAB(R) 9.13 (R2022b) and Automated Driving Toolbox 3.6 (R2022b).
% Generated on: 03-Apr-2023 05:09:57

% Create the drivingScenario object and ego car
[scenario, egoVehicle] = createDrivingScenario;

% Create all the sensors
[sensors, numSensors] = createSensors(scenario);

allData = struct('Time', {}, 'ActorPoses', {}, 'ObjectDetections', {}, 'LaneDetections', {}, 'PointClouds', {}, 'INSMeasurements', {});
running = true;
while running

    % Generate the target poses of all actors relative to the ego vehicle
    poses = targetPoses(egoVehicle);
    time  = scenario.SimulationTime;

    objectDetections = {};
    laneDetections   = [];
    ptClouds = {};
    insMeas = {};
    isValidTime = false(1, numSensors);
    isValidLaneTime = false(1, numSensors);
    isValidPointCloudTime = false(1, numSensors);
    isValidINSTime = false(1, numSensors);

    % Generate detections for each sensor
    for sensorIndex = 1:numSensors
        sensor = sensors{sensorIndex};
        % Generate the ego vehicle lane boundaries
        if isa(sensor, 'visionDetectionGenerator')
            maxLaneDetectionRange = min(500,sensor.MaxRange);
            lanes = laneBoundaries(egoVehicle, 'XDistance', linspace(-maxLaneDetectionRange, maxLaneDetectionRange, 101));
        end
        type = getDetectorOutput(sensor);
        if strcmp(type, 'Objects only')
            if isa(sensor,'ultrasonicDetectionGenerator')
                [objectDets, isValidTime(sensorIndex)] = sensor(poses, time);
                numObjects = length(objectDets);
            else
                [objectDets, numObjects, isValidTime(sensorIndex)] = sensor(poses, time);
            end
            objectDetections = [objectDetections; objectDets(1:numObjects)]; %#ok<AGROW>
        elseif strcmp(type, 'Lanes only')
            [laneDets, ~, isValidTime(sensorIndex)] = sensor(lanes, time);
            laneDetections   = [laneDetections laneDets]; %#ok<AGROW>
        elseif strcmp(type, 'Lanes and objects')
            [objectDets, numObjects, isValidTime(sensorIndex), laneDets, ~, isValidLaneTime(sensorIndex)] = sensor(poses, lanes, time);
            objectDetections = [objectDetections; objectDets(1:numObjects)]; %#ok<AGROW>
            laneDetections   = [laneDetections laneDets]; %#ok<AGROW>
        elseif strcmp(type, 'Lanes with occlusion')
            [laneDets, ~, isValidLaneTime(sensorIndex)] = sensor(poses, lanes, time);
            laneDetections   = [laneDetections laneDets]; %#ok<AGROW>
        elseif strcmp(type, 'PointCloud')
            if sensor.HasRoadsInputPort
                rdmesh = roadMesh(egoVehicle,min(500,sensor.MaxRange));
                [ptCloud, isValidPointCloudTime(sensorIndex)] = sensor(poses, rdmesh, time);
            else
                [ptCloud, isValidPointCloudTime(sensorIndex)] = sensor(poses, time);
            end
            ptClouds = [ptClouds; ptCloud]; %#ok<AGROW>
        elseif strcmp(type, 'INSMeasurement')
            insMeasCurrent = sensor(actorState, time);
            insMeas = [insMeas; insMeasCurrent]; %#ok<AGROW>
            isValidINSTime(sensorIndex) = true;
        end
    end

    % Aggregate all detections into a structure for later use
    if any(isValidTime) || any(isValidLaneTime) || any(isValidPointCloudTime) || any(isValidINSTime)
        allData(end + 1) = struct( ...
            'Time',       scenario.SimulationTime, ...
            'ActorPoses', actorPoses(scenario), ...
            'ObjectDetections', {objectDetections}, ...
            'LaneDetections', {laneDetections}, ...
            'PointClouds',   {ptClouds}, ... %#ok<AGROW>
            'INSMeasurements',   {insMeas}); %#ok<AGROW>
    end

    % Advance the scenario one time step and exit the loop if the scenario is complete
    running = advance(scenario);
end

% Restart the driving scenario to return the actors to their initial positions.
restart(scenario);

% Release all the sensor objects so they can be used again.
for sensorIndex = 1:numSensors
    release(sensors{sensorIndex});
end

%%%%%%%%%%%%%%%%%%%%
% Helper functions %
%%%%%%%%%%%%%%%%%%%%

% Units used in createSensors and createDrivingScenario
% Distance/Position - meters
% Speed             - meters/second
% Angles            - degrees
% RCS Pattern       - dBsm

function [sensors, numSensors] = createSensors(scenario)
% createSensors Returns all sensor objects to generate detections

% Assign into each sensor the physical and radar profiles for all actors
profiles = actorProfiles(scenario);
sensors{1} = visionDetectionGenerator('SensorIndex', 1, ...
    'UpdateInterval', 0.01, ...
    'SensorLocation', [1.918 0], ...
    'MinObjectImageSize', [2 2], ...
    'DetectorOutput', 'Lanes and objects', ...
    'Intrinsics', cameraIntrinsics([200 799.999999999999],[320 240],[480 640]), ...
    'ActorProfiles', profiles);
sensors{2} = drivingRadarDataGenerator('SensorIndex', 2, ...
    'UpdateRate', 100, ...
    'MountingLocation', [3.729 0 0.2], ...
    'RangeLimits', [0 100], ...
    'TargetReportFormat', 'Detections', ...
    'FieldOfView', [180 5], ...
    'Profiles', profiles);
numSensors = 2;

function [scenario, egoVehicle] = createDrivingScenario
% createDrivingScenario Returns the drivingScenario defined in the Designer

% Construct a drivingScenario object.
scenario = drivingScenario('StopTime', 60, ...
    'GeographicReference', [42.30084 -83.69825 0], ...
    'VerticalAxis', 'Y');

% Add all road segments
roadCenters = [-32.5 -11.5 -8.3837679302867e-05;
    -32.175876841361 -50.007748031824 -0.00027750478016486];
laneSpecification = lanespec([1 1]);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'State Street');

roadCenters = [12.2 -50.4 -0.00025546348390293;
    -32.175876841361 -50.007748031824 -0.00027750478016486];
laneSpecification = lanespec([1 1]);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Liberty Street');

roadCenters = [-32.175876841361 -50.007748031824 -0.00027750478016486;
    -31.9 -108.5 -0.00050680780822887];
laneSpecification = lanespec([1 1]);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'State Street');

roadCenters = [-32.175876841361 -50.007748031824 -0.00027750478016486;
    -66.3 -50.6 -0.00064249175300546];
laneSpecification = lanespec([1 1]);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Liberty Street');

roadCenters = [-30.53 -42.33 0;
    -28.56 -45.88 0;
    -26.12 -48.24 0];
laneSpecification = lanespec(1);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road');

roadCenters = [-34.17 -42.38 0;
    -36.02 -46.11 0;
    -39.55 -48.66 0];
laneSpecification = lanespec(1);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road1');

roadCenters = [-39.21 -51.75 0;
    -35.5 -53.47 0;
    -33.92 -56.61 0];
laneSpecification = lanespec(1);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road2');

roadCenters = [-24.47 -51.75 0;
    -28.34 -53.75 0;
    -30.63 -58.76 0];
laneSpecification = lanespec(1);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road3');

% Add the ego vehicle
egoVehicle = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [-30 -105.7 0], ...
    'Mesh', driving.scenario.carMesh, ...
    'PlotColor', [0 114 189] / 255, ...
    'Name', 'Car');
waypoints = [-30 -105.7 0;
    -30.1 -101.7 0;
    -30.15 -96.99 0.01;
    -30.21 -92.19 0.01;
    -30.3 -86.77 0.01;
    -30.3 -80 0;
    -30.32 -73.22 0.01;
    -30.45 -66.63 0.01;
    -30.5 -61.5 0;
    -30.57 -54.55 0.01;
    -30.57 -49.76 0.01;
    -30.57 -43.39 0.01;
    -30.6 -36.1 0.01;
    -30.7 -29.94 0.01;
    -30.67 -23.9 0.01;
    -30.7 -18.37 0.01;
    -30.67 -13.67 0.01];
speed = [30;30;30;30;30;30;30;30;30;30;30;30;30;30;30;30;30];
trajectory(egoVehicle, waypoints, speed);

% Add the non-ego actors
car1 = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [7.47875627690581 -48.1938520883004 0], ...
    'Mesh', driving.scenario.carMesh, ...
    'PlotColor', [0.494 0.184 0.556], ...
    'Name', 'Car1');
waypoints = [7.47875627690581 -48.1938520883004 0;
    -21.43 -48.2 0.01;
    -30.06 -48.21 0.01;
    -38.13 -48.33 0.01;
    -47.08 -48.54 0.01;
    -57.2 -48.62 0.01];
speed = [15;0;15;15;15;15];
waittime = [0;1;0;0;0;0];
trajectory(car1, waypoints, speed, waittime);

actor(scenario, ...
    'ClassID', 7, ...
    'Length', 1, ...
    'Width', 1, ...
    'Height', 1, ...
    'Position', [-27.4 -60.11 0], ...
    'PlotColor', [255 0 0] / 255, ...
    'Name', 'Stop Sign');

actor(scenario, ...
    'ClassID', 7, ...
    'Length', 1, ...
    'Width', 1, ...
    'Height', 1, ...
    'Position', [-22.0133333333333 -45.18 0], ...
    'PlotColor', [255 0 0] / 255, ...
    'Name', 'Stop Sign1');

actor(scenario, ...
    'ClassID', 7, ...
    'Length', 1, ...
    'Width', 1, ...
    'Height', 1, ...
    'Position', [-37.2966666666667 -40.1 0], ...
    'PlotColor', [255 0 0] / 255, ...
    'Name', 'Stop Sign2');

actor(scenario, ...
    'ClassID', 7, ...
    'Length', 1, ...
    'Width', 1, ...
    'Height', 1, ...
    'Position', [-41.5 -55.05 0], ...
    'PlotColor', [255 0 0] / 255, ...
    'Name', 'Stop Sign3');

function output = getDetectorOutput(sensor)

if isa(sensor, 'visionDetectionGenerator')
    output = sensor.DetectorOutput;
elseif isa(sensor, 'lidarPointCloudGenerator')
    output = 'PointCloud';
elseif isa(sensor, 'insSensor')
    output = 'INSMeasurement';
else
    output = 'Objects only';
end

