function [allData, scenario, sensors] = scenario_RA_intersection()
%scenario_RA_intersection - Returns sensor detections
%    allData = scenario_RA_intersection returns sensor detections in a structure
%    with time for an internally defined scenario and sensor suite.
%
%    [allData, scenario, sensors] = scenario_RA_intersection optionally returns
%    the drivingScenario and detection generator objects.

% Generated by MATLAB(R) 9.13 (R2022b) and Automated Driving Toolbox 3.6 (R2022b).
% Generated on: 30-Mar-2023 15:17:34

% Create the drivingScenario object and ego car
[scenario, egoVehicle] = createDrivingScenario;

% Create all the sensors
[sensors, numSensors] = createSensors(scenario);

allData = struct('Time', {}, 'ActorPoses', {}, 'ObjectDetections', {}, 'LaneDetections', {}, 'PointClouds', {}, 'INSMeasurements', {});
running = true;
while running

    % Generate the target poses of all actors relative to the ego vehicle
    poses = targetPoses(egoVehicle);
    time  = scenario.SimulationTime;

    objectDetections = {};
    laneDetections   = [];
    ptClouds = {};
    insMeas = {};
    isValidTime = false(1, numSensors);
    isValidLaneTime = false(1, numSensors);
    isValidPointCloudTime = false(1, numSensors);
    isValidINSTime = false(1, numSensors);

    % Generate detections for each sensor
    for sensorIndex = 1:numSensors
        sensor = sensors{sensorIndex};
        % Generate the ego vehicle lane boundaries
        if isa(sensor, 'visionDetectionGenerator')
            maxLaneDetectionRange = min(500,sensor.MaxRange);
            lanes = laneBoundaries(egoVehicle, 'XDistance', linspace(-maxLaneDetectionRange, maxLaneDetectionRange, 101));
        end
        type = getDetectorOutput(sensor);
        if strcmp(type, 'Objects only')
            if isa(sensor,'ultrasonicDetectionGenerator')
                [objectDets, isValidTime(sensorIndex)] = sensor(poses, time);
                numObjects = length(objectDets);
            else
                [objectDets, numObjects, isValidTime(sensorIndex)] = sensor(poses, time);
            end
            objectDetections = [objectDetections; objectDets(1:numObjects)]; %#ok<AGROW>
        elseif strcmp(type, 'Lanes only')
            [laneDets, ~, isValidTime(sensorIndex)] = sensor(lanes, time);
            laneDetections   = [laneDetections laneDets]; %#ok<AGROW>
        elseif strcmp(type, 'Lanes and objects')
            [objectDets, numObjects, isValidTime(sensorIndex), laneDets, ~, isValidLaneTime(sensorIndex)] = sensor(poses, lanes, time);
            objectDetections = [objectDetections; objectDets(1:numObjects)]; %#ok<AGROW>
            laneDetections   = [laneDetections laneDets]; %#ok<AGROW>
        elseif strcmp(type, 'Lanes with occlusion')
            [laneDets, ~, isValidLaneTime(sensorIndex)] = sensor(poses, lanes, time);
            laneDetections   = [laneDetections laneDets]; %#ok<AGROW>
        elseif strcmp(type, 'PointCloud')
            if sensor.HasRoadsInputPort
                rdmesh = roadMesh(egoVehicle,min(500,sensor.MaxRange));
                [ptCloud, isValidPointCloudTime(sensorIndex)] = sensor(poses, rdmesh, time);
            else
                [ptCloud, isValidPointCloudTime(sensorIndex)] = sensor(poses, time);
            end
            ptClouds = [ptClouds; ptCloud]; %#ok<AGROW>
        elseif strcmp(type, 'INSMeasurement')
            insMeasCurrent = sensor(actorState, time);
            insMeas = [insMeas; insMeasCurrent]; %#ok<AGROW>
            isValidINSTime(sensorIndex) = true;
        end
    end

    % Aggregate all detections into a structure for later use
    if any(isValidTime) || any(isValidLaneTime) || any(isValidPointCloudTime) || any(isValidINSTime)
        allData(end + 1) = struct( ...
            'Time',       scenario.SimulationTime, ...
            'ActorPoses', actorPoses(scenario), ...
            'ObjectDetections', {objectDetections}, ...
            'LaneDetections', {laneDetections}, ...
            'PointClouds',   {ptClouds}, ... %#ok<AGROW>
            'INSMeasurements',   {insMeas}); %#ok<AGROW>
    end

    % Advance the scenario one time step and exit the loop if the scenario is complete
    running = advance(scenario);
end

% Restart the driving scenario to return the actors to their initial positions.
restart(scenario);

% Release all the sensor objects so they can be used again.
for sensorIndex = 1:numSensors
    release(sensors{sensorIndex});
end

%%%%%%%%%%%%%%%%%%%%
% Helper functions %
%%%%%%%%%%%%%%%%%%%%

% Units used in createSensors and createDrivingScenario
% Distance/Position - meters
% Speed             - meters/second
% Angles            - degrees
% RCS Pattern       - dBsm

function [sensors, numSensors] = createSensors(scenario)
% createSensors Returns all sensor objects to generate detections

% Assign into each sensor the physical and radar profiles for all actors
profiles = actorProfiles(scenario);
sensors{1} = visionDetectionGenerator('SensorIndex', 1, ...
    'UpdateInterval', 0.01, ...
    'SensorLocation', [1.918 0], ...
    'MinObjectImageSize', [2 2], ...
    'DetectorOutput', 'Lanes and objects', ...
    'Intrinsics', cameraIntrinsics([200 799.999999999999],[320 240],[480 640]), ...
    'ActorProfiles', profiles);
sensors{2} = drivingRadarDataGenerator('SensorIndex', 2, ...
    'UpdateRate', 100, ...
    'MountingLocation', [3.729 0 0.2], ...
    'RangeLimits', [0 100], ...
    'TargetReportFormat', 'Detections', ...
    'FieldOfView', [180 5], ...
    'Profiles', profiles);
numSensors = 2;

function [scenario, egoVehicle] = createDrivingScenario
% createDrivingScenario Returns the drivingScenario defined in the Designer

% Construct a drivingScenario object.
scenario = drivingScenario('StopTime', 60, ...
    'GeographicReference', [42.30084 -83.69825 0], ...
    'VerticalAxis', 'Y');

% Add all road segments
roadCenters = [-32.711356950045 59.360765369327 -0.00036058797906691;
    -32.612500355933 39.16657774365 -0.00020376710189751];
laneSpecification = lanespec([1 1]);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'State Street');

roadCenters = [-23.014142891089 81.843145029033 -0.00056769333578188;
    -18.759277146568 86.208542704077 -0.00061141550324351;
    -12.566644585482 91.595867383535 -0.00067148498452951;
    -8.1 94.5 -0.00080291223482476];
laneSpecification = lanespec([1 1]);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Pontiac Trail');

roadCenters = [-32.711356950045 59.360765369327 -0.00036058797906691;
    -28.233848495247 59.938357456009 -0.00034464113073085;
    -24.209858327928 61.993306503338 -0.00034780710060289;
    -21.134140951688 65.281239108792 -0.00036976692330626;
    -19.353023649525 69.413377998724 -0.00040784890251189;
    -19.080898209806 73.900974560048 -0.00045755533614056;
    -20.350746701828 78.2108488363 -0.0005129792556744;
    -23.014142891089 81.843145029033 -0.00056769333578188];
laneSpecification = lanespec([1 1]);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', '453870101');

roadCenters = [-23.014142891089 81.843145029033 -0.00056769333578188;
    -26.18878335477 84.098062762283 -0.00060931748304682;
    -29.891159676971 85.319948129265 -0.00064183173781629;
    -33.791440222768 85.408829134728 -0.00066246574172624;
    -37.53505594484 84.342488375977 -0.00066914504104432;
    -40.808666018275 82.232002920298 -0.00066160099093082;
    -43.32366576073 79.266204878441 -0.00064053377333551;
    -44.840923952971 75.689466025318 -0.000607462665144;
    -45.236749589638 71.823914437478 -0.00056545581224299];
laneSpecification = lanespec([1 1]);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', '453870101');

roadCenters = [-45.236749589638 71.823914437478 -0.00056545581224299;
    -44.494646827481 68.036110988847 -0.00051862372449563;
    -42.664087130341 64.637077931712 -0.00047070850585129;
    -39.926476672629 61.904514987985 -0.00042584461720807;
    -36.504452196692 60.105014301263 -0.00038812307889913;
    -32.711356950045 59.360765369327 -0.00036058797906691];
laneSpecification = lanespec([1 1]);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', '453870101');

roadCenters = [-17.9 83.2 0;
    -18.333333333333 80.466666666667 0;
    -17.3 78.1 0];
laneSpecification = lanespec(1, 'Width', 2);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road22');

roadCenters = [-20.5 88.3 0;
    -21.4 87.6 0;
    -27.6 87.2 0];
laneSpecification = lanespec(1, 'Width', 2);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road23');

roadCenters = [-24.8 58.7 0;
    -29 56.3 0;
    -29.9 54.4 0];
laneSpecification = lanespec(1, 'Width', 2);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road24');

roadCenters = [-38 57.9 0;
    -35.9 56.1 0;
    -35 54.6 0];
laneSpecification = lanespec(1, 'Width', 2);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road25');

roadCenters = [-46.5 78.3 0;
    -48 75.8 0;
    -52.1 73.2 0];
laneSpecification = lanespec(1, 'Width', 2);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road26');

roadCenters = [-53.6 67.8 0;
    -50.1 68.5 0;
    -46.3 65.9 0];
laneSpecification = lanespec(1, 'Width', 2);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road27');

roadCenters = [-45.5 71.9 -0.00036058797906691;
    -59.2 68.6 0;
    -68.2 64.6 -0.00020376710189751];
laneSpecification = lanespec([1 1]);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'State Street');

% Add the ego vehicle
egoVehicle = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [-30.9 41 0], ...
    'Mesh', driving.scenario.carMesh, ...
    'PlotColor', [0 114 189] / 255, ...
    'Name', 'Car');
waypoints = [-30.9 41 0;
    -30.8 45.2 0;
    -30.85 50.05 0.01;
    -30.89 54.27 0.01;
    -30.02 56.88 0.01;
    -27.33 58.31 0.01;
    -23.24 60.49 0.01;
    -19.89 63.92 0.01;
    -17.63 68.44 0.01;
    -17.11 72.53 0.01;
    -17.5 76.18 0.01;
    -18.63 78.7 0.01;
    -19.67 81.57 0.01;
    -18.54 84.18 0.01;
    -16.89 85.96 0.01;
    -14.07 88.48 0.01];
speed = [30;30;30;30;30;30;30;30;30;30;30;30;30;30;30;30];
trajectory(egoVehicle, waypoints, speed);

% Add the non-ego actors
car1 = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [-47.37 68.83 0.01], ...
    'Mesh', driving.scenario.carMesh, ...
    'Name', 'Car1');
waypoints = [-47.37 68.83 0.01;
    -45.37 65.22 0.01;
    -43.19 62.27 0.01;
    -40.58 60.18 0.01;
    -37.45 58.57 0.01;
    -33.59 57.7 0.01;
    -28.11 57.92 0.01;
    -23.41 60.05 0.01;
    -20.07 63.62 0.01;
    -17.94 67.22 0.01;
    -17.28 70.4 0.01;
    -17.15 74.53 0.01;
    -18.2 78.44 0.01;
    -19.54 80.7 0.01;
    -22.07 83.74 0.01;
    -26.11 86.05 0.01;
    -30.85 87.22 0.01;
    -34.54 87.05 0.01;
    -37.93 85.96 0.01];
speed = [10;10;10;10;10;10;10;10;10;10;10;10;10;10;10;10;10;10;10];
trajectory(car1, waypoints, speed);

actor(scenario, ...
    'ClassID', 9, ...
    'Length', 1, ...
    'Width', 1, ...
    'Height', 1, ...
    'Position', [-27.8766666666667 53.26 0], ...
    'PlotColor', [0.494 0.184 0.556], ...
    'Name', 'Roundabout');

actor(scenario, ...
    'ClassID', 9, ...
    'Length', 1, ...
    'Width', 1, ...
    'Height', 1, ...
    'Position', [-53.95 65 0], ...
    'Name', 'Roundabout1');

actor(scenario, ...
    'ClassID', 9, ...
    'Length', 1, ...
    'Width', 1, ...
    'Height', 1, ...
    'Position', [-20.9633333333333 91.31 0], ...
    'PlotColor', [0.494 0.184 0.556], ...
    'Name', 'Roundabout2');

function output = getDetectorOutput(sensor)

if isa(sensor, 'visionDetectionGenerator')
    output = sensor.DetectorOutput;
elseif isa(sensor, 'lidarPointCloudGenerator')
    output = 'PointCloud';
elseif isa(sensor, 'insSensor')
    output = 'INSMeasurement';
else
    output = 'Objects only';
end

