function [allData, scenario, sensor] = EgoVehicleGoesStraight_PedestrianToRightGoesStraight()
%EgoVehicleGoesStraight_PedestrianToRightGoesStraight - Returns sensor detections
%    allData = EgoVehicleGoesStraight_PedestrianToRightGoesStraight returns sensor detections in a structure
%    with time for an internally defined scenario and sensor suite.
%
%    [allData, scenario, sensors] = EgoVehicleGoesStraight_PedestrianToRightGoesStraight optionally returns
%    the drivingScenario and detection generator objects.

% Generated by MATLAB(R) 9.13 (R2022b) and Automated Driving Toolbox 3.6 (R2022b).
% Generated on: 04-Dec-2022 19:00:51

% Create the drivingScenario object and ego car
[scenario, egoVehicle] = createDrivingScenario;

% Create all the sensors
sensor = createSensor(scenario);

allData = struct('Time', {}, 'ActorPoses', {}, 'ObjectDetections', {}, 'LaneDetections', {}, 'PointClouds', {}, 'INSMeasurements', {});
running = true;
while running

    % Generate the target poses of all actors relative to the ego vehicle
    poses = targetPoses(egoVehicle);
    time  = scenario.SimulationTime;

    % Generate the ego vehicle lane boundaries
    if isa(sensor, 'visionDetectionGenerator')
        maxLaneDetectionRange = min(500,sensor.MaxRange);
        lanes = laneBoundaries(egoVehicle, 'XDistance', linspace(-maxLaneDetectionRange, maxLaneDetectionRange, 101));
    end
    % Generate detections for the sensor
    ptClouds = [];
    insMeas = [];
    [objectDetections, numObjects, isValidTime, laneDetections, ~, isValidLaneTime] = sensor(poses, lanes, time);
    objectDetections = objectDetections(1:numObjects);

    % Aggregate all detections into a structure for later use
    if isValidTime || isValidLaneTime
        allData(end + 1) = struct( ...
            'Time',       scenario.SimulationTime, ...
            'ActorPoses', actorPoses(scenario), ...
            'ObjectDetections', {objectDetections}, ...
            'LaneDetections', {laneDetections}, ...
            'PointClouds',   {ptClouds}, ... %#ok<AGROW>
            'INSMeasurements',   {insMeas}); %#ok<AGROW>
    end

    % Advance the scenario one time step and exit the loop if the scenario is complete
    running = advance(scenario);
end

% Restart the driving scenario to return the actors to their initial positions.
restart(scenario);

% Release the sensor object so it can be used again.
release(sensor);

%%%%%%%%%%%%%%%%%%%%
% Helper functions %
%%%%%%%%%%%%%%%%%%%%

% Units used in createSensors and createDrivingScenario
% Distance/Position - meters
% Speed             - meters/second
% Angles            - degrees
% RCS Pattern       - dBsm

function sensor = createSensor(scenario)
% createSensors Returns all sensor objects to generate detections

% Assign into each sensor the physical and radar profiles for all actors
profiles = actorProfiles(scenario);
sensor = visionDetectionGenerator('SensorIndex', 1, ...
    'SensorLocation', [1.13 0], ...
    'MaxSpeed', 50, ...
    'MinLaneImageSize', [1 1], ...
    'LaneBoundaryAccuracy', 1, ...
    'MaxNumLanesSource', 'Property', ...
    'MaxNumLanes', 10, ...
    'DetectorOutput', 'Lanes and objects', ...
    'Intrinsics', cameraIntrinsics([800 799.999999999999],[320 240],[480 640]), ...
    'ActorProfiles', profiles);

function [scenario, egoVehicle] = createDrivingScenario
% createDrivingScenario Returns the drivingScenario defined in the Designer

% Construct a drivingScenario object.
scenario = drivingScenario('SampleTime', 0.025);

% Add all road segments
roadCenters = [159 24.2 0;
    51 24.2 0];
laneSpecification = lanespec([2 2], 'Width', [4 3.6 3.6 3.6]);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road');

% Add the ego vehicle
egoVehicle = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [53.1 22.2 0], ...
    'Mesh', driving.scenario.carMesh, ...
    'Name', 'EgoCar');
waypoints = [52.6 19.8 0;
    76.4 19.6 0;
    85.5 19.7 0;
    99.6 19.8 0;
    119.6 19.8 0;
    129.4 19.9 0;
    136.8 20.1 0;
    149.6 19.8 0];
speed = [20;11.25;6.875;2.5;16;16;16;16];
trajectory(egoVehicle, waypoints, speed);

